imports:
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Processing.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml' }
    - { resource: 'EXT:bootstrap_package/Configuration/RTE/Default.yaml' }

editor:
    config:
        contentsCss: 'EXT:bootstrap_package/Resources/Public/Css/bootstrap5-rte.min.css'
        stylesSet:
            - { name: 'wie h1', element: 'div', attributes: { 'class': 'h1' } }
            - { name: 'wie h2', element: 'div', attributes: { 'class': 'h2' } }
            - { name: 'wie h3', element: 'div', attributes: { 'class': 'h3' } }
            - { name: 'wie h4', element: 'div', attributes: { 'class': 'h4' } }
        extraPlugins:
            - find
            - wordcount
            - autolink
            - autogrow
            - codesnippet
        codeSnippet_theme: 'obsidian'
        codeSnippet_languages:
            bash: 'Bash'
            html: 'HTML'
            javascript: 'JavaScript'
            php: 'PHP'
            css: 'CSS'
            scss: 'SCSS'
            typoscript: 'TypoScript'
            yaml: 'Yaml'
            xml: 'XML'
