base: '%env(SITE_BASE)%'
errorHandling:
    - errorCode: 404
      errorHandler: Page
      errorContentSource: 't3://page?uid=7'
languages:
    - title: Deutsch
      enabled: true
      languageId: 0
      base: /
      typo3Language: de
      locale: de_DE.UTF-8
      iso-639-1: de
      navigationTitle: Deutsch
      hreflang: de-DE
      direction: ltr
      flag: de
    - title: English
      enabled: true
      languageId: 1
      base: /en/
      typo3Language: default
      locale: en_US.UTF-8
      iso-639-1: en
      navigationTitle: English
      hreflang: en-US
      direction: ltr
      fallbackType: fallback
      fallbacks: '0'
      flag: en-us-gb
rootPageId: 1
routeEnhancers:
    PageTypeSuffix:
        type: PageType
        default: /
        map:
            /: 0
            sitemap.xml: 1533906435
    News:
        type: Extbase
        extension: News
        plugin: Pi1
        routes:
            - routePath: '/'
              _controller: 'News::list'
            - routePath: '/page-{page}'
              _controller: 'News::list'
              _arguments:
                  page: 'currentPage'
            - routePath: '/{news-title}'
              _controller: 'News::detail'
              _arguments:
                  news-title: news
            - routePath: '/{category-name}'
              _controller: 'News::list'
              _arguments:
                  category-name: overwriteDemand/categories
            - routePath: '/{tag-name}'
              _controller: 'News::list'
              _arguments:
                  tag-name: overwriteDemand/tags
        defaultController: 'News::list'
        defaults:
            page: '0'
        aspects:
            news-title:
                type: PersistedAliasMapper
                tableName: tx_news_domain_model_news
                routeFieldName: path_segment
            page:
                type: StaticRangeMapper
                start: '1'
                end: '100'
            category-name:
                type: PersistedAliasMapper
                tableName: sys_category
                routeFieldName: slug
            tag-name:
                type: PersistedAliasMapper
                tableName: tx_news_domain_model_tag
                routeFieldName: slug
routes:
    - route: robots.txt
      type: staticText
      content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nDisallow: /content-examples/\r\nDisallow: /en/content-examples/\r\n# Keine Backups \r\nDisallow: *.tar.gz\r\nDisallow: *.sql\r\nDisallow: *.sql.gz\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
    - route: sitemap.xml
      type: uri
      source: 't3://page?uid=1&type=1533906435'
websiteTitle: ''
